apiVersion: v1
kind: Secret
metadata:
  name: application-login
  namespace: application
  annotations:
    secret-generator.v1.mittwald.de/type: string
    secret-generator.v1.mittwald.de/autogenerate: password
    secret-generator.v1.mittwald.de/encoding: base64url
    secret-generator.v1.mittwald.de/length: "40"
type: Opaque
stringData:
  username: service-account
