apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: application-login
  namespace: application
spec:
  type: Opaque
  data:
    username: service-account
  fields:
    - fieldName: password
      encoding: base64url
      length: "40"
  rotationInterval: 24h
  forceRegenerate: false
