package secret

import (
	"crypto/rand"
	"encoding/base32"
	"encoding/base64"
	"encoding/hex"
	"strings"

	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"
)

type StringGenerator struct{}

type secretConfig struct {
	instance     *corev1.Secret
	key          string
	length       int
	isByteLength bool
}

func (pg StringGenerator) generateData(instance *corev1.Secret) (reconcile.Result, error) {
	toGenerate := instance.Annotations[AnnotationSecretAutoGenerate]

	genKeys := strings.Split(toGenerate, ",")

	if err := ValidateManagedFields(genKeys, nil); err != nil {
		return reconcile.Result{}, err
	}

	return pg.regenerateKeysWhereRequired(instance, genKeys)
}

func (pg StringGenerator) generateRandomSecret(conf secretConfig) error {
	key := conf.key
	instance := conf.instance
	length := conf.length
	isByteLength := conf.isByteLength

	encoding, err := getEncodingFromAnnotation(DefaultEncoding(), instance.Annotations)
	if err != nil {
		return err
	}
	value, err := GenerateRandomString(length, encoding, isByteLength)
	if err != nil {
		return err
	}
	instance.Data[key] = value

	return nil
}

// GenerateRandomString generates a random string of given length and with given encoding.
// If lenBytes is true, resultring string will not be trimmed
func GenerateRandomString(length int, encoding string, lenBytes bool) ([]byte, error) {
	if err := ValidateLength(length); err != nil {
		return nil, err
	}
	if err := ValidateEncoding(encoding); err != nil {
		return nil, err
	}

	b := make([]byte, length)
	_, err := rand.Read(b)
	if err != nil {
		return []byte{}, err
	}

	var encodedString string
	switch encoding {
	case "base64url":
		encodedString = base64.URLEncoding.EncodeToString(b)
	case "raw":
		return b, nil
	case "base32":
		encodedString = base32.StdEncoding.EncodeToString(b)
	case "hex":
		encodedString = hex.EncodeToString(b)
	case "base64":
		encodedString = base64.StdEncoding.EncodeToString(b)
	}
	// if length was specified with B suffix, don't trim result string
	if lenBytes {
		return []byte(encodedString), nil
	}

	return []byte(encodedString[0:length]), nil
}

func contains(s []string, e string) bool {
	for _, a := range s {
		if a == e {
			return true
		}
	}
	return false
}

func (pg StringGenerator) regenerateKeysWhereRequired(instance *corev1.Secret, genKeys []string) (reconcile.Result, error) {
	var regenKeys []string
	regenerateRequested := false

	if regenerate, ok := instance.Annotations[AnnotationSecretRegenerate]; ok {
		regenerateRequested = true
		var err error
		regenKeys, err = ParseRegenerate(regenerate, genKeys, true)
		if err != nil {
			return reconcile.Result{}, err
		}
	}
	if _, ok := instance.Annotations[AnnotationSecretSecure]; !ok && RegenerateInsecure() {
		regenKeys = genKeys // regenerate all keys
	}

	length, err := GetLengthFromAnnotation(DefaultLength(), instance.Annotations)
	if err != nil {
		return reconcile.Result{}, err
	}

	parsedLength, isByteLength, err := ParseByteLength(DefaultLength(), length)
	if err != nil {
		return reconcile.Result{}, err
	}
	encoding, err := getEncodingFromAnnotation(DefaultEncoding(), instance.Annotations)
	if err != nil {
		return reconcile.Result{}, err
	}
	if err := ValidateEncoding(encoding); err != nil {
		return reconcile.Result{}, err
	}
	valueLength, err := EncodedOutputLength(parsedLength, encoding, isByteLength)
	if err != nil {
		return reconcile.Result{}, err
	}
	projectedValues := make(map[string]int, len(genKeys))
	for _, key := range genKeys {
		if len(instance.Data[key]) == 0 || contains(regenKeys, key) {
			projectedValues[key] = valueLength
		}
	}
	if err := ValidateProjectedDataSize(instance, projectedValues); err != nil {
		return reconcile.Result{}, err
	}

	generatedCount := 0
	for _, key := range genKeys {
		if len(instance.Data[key]) != 0 && !contains(regenKeys, key) {
			// dont generate key if it already has a value
			// and is not queued for regeneration
			continue
		}
		generatedCount++

		err = pg.generateRandomSecret(secretConfig{instance, key, parsedLength, isByteLength})
		if err != nil {
			return reconcile.Result{}, err
		}
	}

	if generatedCount == len(genKeys) {
		// all keys have been generated by this instance
		instance.Annotations[AnnotationSecretSecure] = "yes"
	}
	if regenerateRequested {
		delete(instance.Annotations, AnnotationSecretRegenerate)
	}

	return reconcile.Result{}, nil
}
