{{- if and .Values.rbac.create (eq .Values.scope.mode "cluster") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubernetes-secret-generator.rbacName" . }}-access
  labels:
    {{- include "kubernetes-secret-generator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  {{- if .Values.crdControllers.enabled }}
  - apiGroups: ["secretgenerator.mittwald.de"]
    resources: ["basicauths", "sshkeypairs", "stringsecrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["secretgenerator.mittwald.de"]
    resources: ["basicauths/status", "sshkeypairs/status", "stringsecrets/status"]
    verbs: ["get", "update", "patch"]
  {{- end }}
{{- end }}
