{{- if and .Values.rbac.create (eq .Values.scope.mode "cluster") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubernetes-secret-generator.rbacName" . }}-access
  labels:
    {{- include "kubernetes-secret-generator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubernetes-secret-generator.rbacName" . }}-access
subjects:
  - kind: ServiceAccount
    name: {{ include "kubernetes-secret-generator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
