{{- include "kubernetes-secret-generator.validate" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubernetes-secret-generator.fullname" . }}
  labels:
    {{- include "kubernetes-secret-generator.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "kubernetes-secret-generator.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "kubernetes-secret-generator.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "kubernetes-secret-generator.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- include "kubernetes-secret-generator.imagePullSecrets" . | nindent 6 }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "kubernetes-secret-generator.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args:
            {{- $args := .Values.args }}
            {{- if not .Values.crdControllers.enabled }}
            {{- $args = append $args "--disable-crd-support" }}
            {{- end }}
            {{- toYaml $args | nindent 12 }}
          ports:
            - name: healthcheck
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8383
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthcheck
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthcheck
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          env:
            - name: WATCH_NAMESPACE
              value: {{ include "kubernetes-secret-generator.watchNamespace" . | quote }}
            - name: REGENERATE_INSECURE
              value: {{ .Values.regenerateInsecure | toString | quote }}
            - name: SECRET_LENGTH
              value: {{ .Values.secretLength | quote }}
            - name: SSH_KEY_ALGORITHM
              value: {{ .Values.sshKeyAlgorithm | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
