{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kubernetes-secret-generator.fullname" . }}
  labels:
    {{- include "kubernetes-secret-generator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "kubernetes-secret-generator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    {{- toYaml .Values.networkPolicy.egress.rules | nindent 4 }}
  {{- end }}
{{- end }}
